"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import Footer from "@/Component/Footer";

import { createContext, useState } from "react";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geist = Geist({
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const MyContext = createContext();

export default function RootLayout({ children }) {
  const [friendData, setFriendData] = useState([]);

  return (
    <html
      data-theme="light"
      lang="en"
      className={`${geist.className} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>

        <MyContext.Provider value={{ friendData, setFriendData }}>
          {children}
          <ToastContainer position="top-center" 
   />
        </MyContext.Provider>

        <Footer></Footer>
      </body>
    </html>
  );
}
